spring:
  application:
    name: Trusted One
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: application
    password: application
    driver-class-name: org.postgresql.Driver

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/master.yml